name: Test

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  test-bot:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13]
        include:
          - os: ubuntu-latest
            container:
              image: ghcr.io/homebrew/brew:latest
    runs-on: ${{ matrix.os }}
    container: ${{ fromJSON(toJSON(matrix.container)) }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae
